spring:
  datasource:
    password: password
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    hibernate:
      ddl-auto: create

mocker:
  methods: GET,POST,PUT,PATCH
  uuid: a79c4bd8-d0e4-11ea-87d0-0242ac130003
  maxDelay: 5000
  path:
    regex: \/\S+\/\S+